name: context variables example

on: 
    push:
        branches:
        - "*"
jobs:
    print-cloud:
        runs-on: ubuntu-latest
        steps:
            - name: Print repo name
              run: echo "I am on this repo ${{ github.repository }}"
            - name: Print workflow name
              run: echo "I am running this workflow ${{ github.workflow }}"
            - name: Triggered by
              run: echo "Triggered by ${{ github.actor }}"
            - name: Using to test the secret variable
              run: echo "THis access key is used to access AWS environment ${{ secrets.AWS_ACCESS_KEY }}"
            - name: Using to test the secret variable-2
              run: echo "THis secret key is used to access AWS environment ${{ secrets.AWS_SECRET_KEY}}"